routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\KeluhanController;
use App\Http\Controllers\PelangganController;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/version', function () {
    return ["version" => "1.0.0"];
});

Route::get('/lang', function () {
    return __("auth.failed");
});

Route::get('/setter/{lang}', function ($lang) {
    session(['lang' => $lang]);
    return $lang;
});

Route::get('/login', [AuthController::class, 'login'])->name('login');
Route::post('/login', [AuthController::class, 'actionLogin']);
Route::get('/logout', [AuthController::class, 'logout'])->name('logout');


Route::get('/admin/pelanggan', function () {
    return view('admin.pelanggan');
});

Route::get('/test', function () {
    $sql = "SELECT * FROM pelanggan WHERE id = :id";
    $result = DB::selectOne($sql, ["id" => 1]);
    dd($result->nama);
    return view('welcome');
});

Route::get('/bootstrap', function () {
    return view('bootstrap');
});

Route::get('/greeting', function () {
    return 'Hello World';
});

Route::get('/keluhan', [KeluhanController::class, 'index']);

Route::get('/keluhan/{name}', [KeluhanController::class, 'detail']);


Route::post('/keluhan', [KeluhanController::class, 'action']);

Route::put('/action-formulir', function () {
    return 'Formulir Berhasil diubah';
});
Route::group(["middleware" => "auth"], function () {
    Route::resource('/pelanggan', PelangganController::class);
    Route::get("/supplier", function () {
        return view("supplier");
    });
    Route::get("/dashboard", function () {
        return view("dashboard");
    });
});

app/Models/Pelanggan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pelanggan extends Model
{
    use HasFactory;
    protected $table = 'pelanggan';
    protected $fillable = ['nama', 'alamat', 'kelamin'];
    
}

app/Http/Controllers/API/PelangganController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Models\Pelanggan;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Response;

class PelangganController extends Controller
{
    public function index(Request $request)
    {
        $input = $request->all();

        // SELECT * FROM 
        $dataPelanggan = Pelanggan::select(["pelanggan.*", "provinces.province_name"])
            ->leftJoin('provinces', 'pelanggan.province_id', '=', 'provinces.id');

        // where kelamin = ?
        if (isset($input["kelamin"])) {
            $dataPelanggan->where("kelamin", $input["kelamin"]);
        }

        if (isset($input["src"])) {
            $dataPelanggan->where("nama", "like", "%" . $input["src"] . "%");
        }

        return Response::json($dataPelanggan->paginate());
    }

    public function store(Request $request)
    {
        // $validated = $request->validate([
        //     'nama' => 'required|min:5|max:100',
        //     'kelamin' => 'required'
        // ]);
        $input = $request->except(["_token"]);

        // INSERT INTO pelanggan(nama,kelamin,alamat) VALUES('');
        $pelanggan = new Pelanggan();
        $pelanggan->nama = $input["nama"] ?? "";
        $pelanggan->phone = $input["phone"] ?? "";
        $pelanggan->kelamin = $input["kelamin"] ?? "L";
        $pelanggan->alamat = $input["alamat"] ?? "";
        $pelanggan->save();

        // $pelanggan = Pelanggan::create($input);

        return Response::json($pelanggan);
    }

    public function show($id)
    {
        $pelanggan = Pelanggan::find($id);

        return Response::json($pelanggan);
    }

    public function update($id)
    {
        $input = request()->except(["_token"]);
        $pelanggan = Pelanggan::find($id);
        $pelanggan->nama = $input["nama"] ?? "";
        $pelanggan->phone = $input["phone"] ?? "";
        $pelanggan->kelamin = $input["kelamin"] ?? "L";
        $pelanggan->alamat = $input["alamat"] ?? "";
        $pelanggan->save();
        
        return Response::json($pelanggan);
    }

    public function destroy($id)
    {
        // SELECT * FROM pelanggan where id=$id
        $pelanggan = Pelanggan::find($id);

        // DELETE pelanggan where id=$id
        $pelanggan->delete();
        return Response::json([
            "message" => "Pelanggan berhasil dihapus"
        ]) ;
    }
}

app/Http/Controllers/PelangganController.php
<?php

namespace App\Http\Controllers;

use App\Models\Pelanggan;
use App\Models\Province;
use Illuminate\Http\Request;

class PelangganController extends Controller
{
    public function index(Request $request)
    {

        $input = $request->all();

        // SELECT * FROM
        $dataPelanggan = Pelanggan::select(["pelanggan.*", "provinces.province_name"])
            ->leftJoin('provinces', 'pelanggan.province_id', '=', 'provinces.id');

        // where kelamin = ?
        if (isset($input["kelamin"])) {
            $dataPelanggan->where("kelamin", $input["kelamin"]);
        }

        if (isset($input["src"])) {
            $dataPelanggan->where("nama", "like", "%" . $input["src"] . "%");
        }


        $data = [
            "kelamin" => $input["kelamin"] ?? "",
            "daftarPelanggan" => $dataPelanggan->paginate(10)
        ];
        return view('pelanggan.index', $data);
    }

    public function create()
    {
        $data = [
            "provinces" => Province::all()
        ];
        return view('pelanggan.create', $data);
    }

    public function store(Request $request)
    {
        $validated = $request->validate([
            'nama' => 'required|min:5|max:100',
            'kelamin' => 'required'
        ]);
        $input = $request->except(["_token"]);

        $pelanggan = new Pelanggan();
        if ($request->hasFile('image_profile')) {

            $pelanggan->image_profile = $request->file("image_profile")->store("profile");
        }


        // INSERT INTO pelanggan(nama,kelamin,alamat) VALUES('');

        $pelanggan->nama = $input["nama"] ?? "";
        $pelanggan->phone = $input["phone"] ?? "";
        $pelanggan->kelamin = $input["kelamin"] ?? "L";
        $pelanggan->alamat = $input["alamat"] ?? "";
        $pelanggan->save();

        // $pelanggan = Pelanggan::create($input);

        return redirect("/pelanggan");
    }

    public function show($id)
    {
        $data = [
            "provinces" => Province::all(),
            "pelanggan" => Pelanggan::find($id)
        ];
        return view('pelanggan.show', $data);
    }

    public function edit($id)
    {
        $data = [
            "provinces" => Province::all(),
            "pelanggan" => Pelanggan::find($id)
        ];
        return view('pelanggan.edit', $data);
    }

    public function update(Request $request, $id)
    {
        $input = $request->all();
        $pelanggan = Pelanggan::find($id);
        $pelanggan->nama = $input["nama"] ?? "";
        $pelanggan->phone = $input["phone"] ?? "";
        $pelanggan->kelamin = $input["kelamin"] ?? "L";
        $pelanggan->alamat = $input["alamat"] ?? "";
        $pelanggan->province_id = $input["province_id"] ?? null;
        // UPDATE pelanggan SET ... WHERE id = $id
        $pelanggan->save();

        return redirect('/pelanggan');
    }

    public function destroy($id)
    {
        // SELECT * FROM pelanggan where id=$id
        $pelanggan = Pelanggan::find($id);

        if (is_null($pelanggan)) {
            return 'Pelanggan tidak terdaftar dalam database';
        }
        // DELETE pelanggan where id=$id
        $pelanggan->delete();
        return 'Pelanggan berhasil dihapus';
    }
}

resources/views/pelanggan/create.blade.php
@extends("template.index")

@section("content")
<form method="POST" action="{{ route('pelanggan.store') }}" enctype="multipart/form-data">
    @csrf
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Tambah Pelanggan</h3>
        </div>
        <div class="card-body">
            <div class="form-group">
                <label for="nama">Nama</label>
                <input type="text" name="nama" class="form-control @error('nama') is-invalid @enderror" id="nama" placeholder="Masukan Nama Pelanggan">
                @error('nama')
                <div class="invalid-feedback">
                    {{ $message }}
                </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="kelamin">Jenis Kelamin</label>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="kelamin" value="L">
                    <label class="form-check-label">Laki laki</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="kelamin" value="P" checked="">
                    <label class="form-check-label">Wanita</label>
                </div>
            </div>
            <div class="form-group">
                <label for="province_id">Provinsi</label>
                <select class="form-control" name="province_id">
                    @foreach($provinces as $province)
                    <option value="{{ $province->id }}">{{ $province->province_name }}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label for="phone">No Telepon</label>
                <input type="text" name="phone" class="form-control" id="phone" placeholder="Masukan No Telepon Pelanggan">
            </div>
            <div class="form-group">
                <label for="phone">Alamat</label>
                <textarea name="alamat" class="form-control" id="alamat" placeholder="Masukan Alamat Pelanggan">

                </textarea>
            </div>

            <div class="form-group">
                <label for="image">Profile</label>
                <input type="file" name="image_profile" class="form-control">
            </div>

        </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</form>
@endsection

resources/views/pelanggan/edit.blade.php
@extends("template.index")

@section("content")
<form method="POST" action="/pelanggan/{{ $pelanggan->id }}">
    @csrf
    @method("PATCH")
    ID : {{ $pelanggan->id }}
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Ubah Pelanggan</h3>
        </div>
        <div class="card-body">
            <div class="form-group">
                <label for="nama">Nama</label>
                <input type="text" value="{{ $pelanggan->nama }}" name="nama" class="form-control @error('nama') is-invalid @enderror" id="nama" placeholder="Masukan Nama Pelanggan">
                @error('nama')
                <div class="invalid-feedback">
                    {{ $message }}
                </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="kelamin">Jenis Kelamin</label>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="kelamin" value="L">
                    <label class="form-check-label">Laki laki</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="kelamin" value="P" checked="">
                    <label class="form-check-label">Wanita</label>
                </div>
            </div>
            <div class="form-group">
                <label for="province_id">Provinsi</label>
                <select class="form-control" name="province_id">
                    @foreach($provinces as $province)
                    <option "{{ $pelanggan->provice_id == $province->id ? "selected" : "" }}" value="{{ $province->id }}">{{ $province->province_name }}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label for="phone">No Telepon</label>
                <input type="text" value="{{ $pelanggan->phone }}" name="phone" class="form-control" id="phone" placeholder="Masukan No Telepon Pelanggan">
            </div>
            <div class="form-group">
                <label for="phone">Alamat</label>
                <textarea name="alamat" class="form-control" id="alamat" placeholder="Masukan Alamat Pelanggan">
                {{ $pelanggan->alamat }}
                </textarea>
            </div>

        </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</form>
@endsection

resources/views/pelanggan/index.blade.php
@extends("template.index")

@section("content")

<script>
    function hapusPelanggan(id) {
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({
                    url: "/pelanggan/" + id,
                    // headers: {
                    //     'X-XSRF-TOKEN': $('meta[name="_token"]').attr('content')
                    // },
                    method: "DELETE", // use "GET" if server does not handle DELETE
                    data: {
                        "_token": "{{csrf_token()}}"
                    },
                    dataType: "html"
                }).done(function(msg) {
                    window.location.href = "/pelanggan"
                }).fail(function(jqXHR, textStatus) {
                    Swal.fire('Terjadi kesalahan')

                });

            }
        })
    }
</script>

<div class="row">
    <div class="col-md-12">

        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Daftar Pelanggan</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <div class="">
                    <a class="btn btn-primary" href="{{ route("pelanggan.create") }}">Tambah Pelanggan</a>
                </div>
                <br />
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Aksi</th>
                            <th>Nama</th>
                            <th>Kelamin</th>
                            <th>No Telepon</th>
                            <th>Provinsi</th>
                            <th>ALamat</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($daftarPelanggan as $pelanggan)
                        <tr>
                            <td>
                                <a href="/pelanggan/{{ $pelanggan["id"] }}" class="btn btn-info">Lihat<a />
                                    <a href="/pelanggan/{{ $pelanggan["id"] }}/edit" class="btn btn-success">Ubah<a />
                                        <button onclick="hapusPelanggan('{{ $pelanggan->id }}')" class="btn btn-danger">Hapus</button>

                            </td>
                            <td>{{ $pelanggan["nama"] }}</td>
                            <td>
                                {{ $pelanggan["kelamin"] == "L" ? "Laki-laki" : "Wanita" }}
                            </td>
                            <td>{{ $pelanggan["phone"] }}</td>
                            <td>{{ $pelanggan["province_name"] }}</td>
                            <td>{{ $pelanggan["alamat"] }}</td>
                        </tr>
                        @endforeach
                        @if(count($daftarPelanggan) == 0)
                        <tr>
                            <td colspan="5">
                                Tidak data pelanggan
                            </td>
                        </tr>
                        @endif
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
            <div class="card-footer clearfix">
                {{ $daftarPelanggan->links() }}
            </div>

        </div>
        <!-- /.card -->

    </div>
</div>

@endsection

resources/views/pelanggan/show.blade.php
@extends("template.index")

@section("content")

ID : {{ $pelanggan->id }}
<div class="card">
    <div class="card-header">
        <h3 class="card-title">Ubah Pelanggan</h3>
    </div>
    <div class="card-body">
        <div class="form-group">
            <label for="nama">Nama</label>
            <input disabled type="text" value="{{ $pelanggan->nama }}" name="nama" class="form-control @error('nama') is-invalid @enderror" id="nama" placeholder="Masukan Nama Pelanggan">
        </div>
        <div class="form-group">
            <label for="kelamin">Jenis Kelamin</label>
            <div class="form-check">
                <input disabled class="form-check-input" type="radio" name="kelamin" value="L">
                <label class="form-check-label">Laki laki</label>
            </div>
            <div class="form-check">
                <input disabled class="form-check-input" type="radio" name="kelamin" value="P" checked="">
                <label class="form-check-label">Wanita</label>
            </div>
        </div>
        <div class="form-group">
            <label for="province_id">Provinsi</label>
            <select disabled class="form-control" name="province_id">
                @foreach($provinces as $province)
                <option "{{ $pelanggan->provice_id == $province->id ? "selected" : "" }}" value="{{ $province->id }}">{{ $province->province_name }}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="phone">No Telepon</label>
            <input disabled type="text" value="{{ $pelanggan->phone }}" name="phone" class="form-control" id="phone" placeholder="Masukan No Telepon Pelanggan">
        </div>
        <div class="form-group">
            <label for="phone">Alamat</label>
            <textarea disabled name="alamat" class="form-control" id="alamat" placeholder="Masukan Alamat Pelanggan">
            {{ $pelanggan->alamat }}
            </textarea>
        </div>
        <div class="form-group">
            <label for="profile">Profile</label>
            @if($pelanggan->image_profile != null)
            <img src="{{ env('MINIO_URL').'/'.env('MINIO_BUCKET').'/'.$pelanggan->image_profile }}" />
            @endif
        </div>

    </div>

</div>
@endsection